/**
 * Formats CodeReviewFindings into GitHub-flavored markdown for PR reviews.
 */

import type { ReviewEvent } from '@funny/core/git';
import type { CodeReviewFinding, ReviewFindingSeverity } from '@funny/shared';

const SEVERITY_EMOJI: Record<ReviewFindingSeverity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  suggestion: '💡',
};

const SEVERITY_ORDER: ReviewFindingSeverity[] = ['critical', 'high', 'medium', 'low', 'suggestion'];

/**
 * Decide the review event based on the highest severity finding.
 */
export function decideReviewEvent(findings: CodeReviewFinding[]): ReviewEvent {
  if (findings.length === 0) return 'APPROVE';

  const hasBlocking = findings.some((f) => f.severity === 'critical' || f.severity === 'high');
  if (hasBlocking) return 'REQUEST_CHANGES';

  const hasMedium = findings.some((f) => f.severity === 'medium');
  if (hasMedium) return 'COMMENT';

  return 'COMMENT';
}

/**
 * Format findings into a markdown review body for GitHub.
 */
export function formatReviewBody(summary: string, findings: CodeReviewFinding[]): string {
  const lines: string[] = [];

  // Header
  lines.push('## ReviewBot');
  lines.push('');

  // Summary
  lines.push(summary);
  lines.push('');

  if (findings.length === 0) {
    lines.push('No issues found. ✅');
    return lines.join('\n');
  }

  // Group by severity
  lines.push(`**${findings.length} finding${findings.length === 1 ? '' : 's'}:**`);
  lines.push('');

  for (const severity of SEVERITY_ORDER) {
    const group = findings.filter((f) => f.severity === severity);
    if (group.length === 0) continue;

    for (const finding of group) {
      const emoji = SEVERITY_EMOJI[finding.severity];
      const location = finding.line ? `\`${finding.file}:${finding.line}\`` : `\`${finding.file}\``;

      lines.push(`${emoji} **${finding.severity}** (${finding.category}) — ${location}`);
      lines.push(`  ${finding.description}`);

      if (finding.suggestion) {
        lines.push(`  > **Suggestion:** ${finding.suggestion}`);
      }

      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [funny](https://github.com/ironmussa/funny) ReviewBot*');

  return lines.join('\n');
}
