/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DiffSummaryResult {
  files: Array<FileDiffSummaryItem>;
  total: number;
  truncated: boolean;
}

export interface FileDiffSummaryItem {
  path: string;
  status: string;
  staged: boolean;
}

export declare function getCurrentBranch(cwd: string): Promise<string | null>;

export declare function getDefaultBranch(cwd: string): Promise<string | null>;

export declare function getDiffSummary(
  cwd: string,
  excludePatterns?: Array<string> | undefined | null,
  maxFiles?: number | undefined | null,
): Promise<DiffSummaryResult>;

export declare function getLog(
  cwd: string,
  limit?: number | undefined | null,
): Promise<Array<GitLogEntry>>;

export declare function getStatusSummary(
  worktreeCwd: string,
  baseBranch?: string | undefined | null,
  projectCwd?: string | undefined | null,
): Promise<GitStatusSummary>;

export interface GitLogEntry {
  hash: string;
  shortHash: string;
  author: string;
  relativeDate: string;
  message: string;
}

export interface GitStatusSummary {
  dirtyFileCount: number;
  unpushedCommitCount: number;
  hasRemoteBranch: boolean;
  isMergedIntoBase: boolean;
  linesAdded: number;
  linesDeleted: number;
}

export declare function listBranches(cwd: string): Promise<Array<string>>;

/** Simple ping function to verify the native module loads correctly. */
export declare function ping(): string;
